# ===== build go binary =====
FROM golang:1.20-alpine as go-builder

WORKDIR /go/src/github.com/docker-container-exercise1/client

COPY client/ .

RUN go mod download

RUN go build -o main main.go

# ==== build docker image ====
FROM alpine

COPY --from=go-builder /go/src/github.com/docker-container-exercise1/client client

ENTRYPOINT ["./client/main"]
