# ===== build go binary =====
FROM golang:1.20-alpine as go-builder

WORKDIR /go/src/github.com/docker-container-exercise1/server

COPY server/ .

RUN go mod download

RUN go build -o main main.go

# ==== build docker image ====
FROM alpine

COPY --from=go-builder /go/src/github.com/docker-container-exercise1/server server

WORKDIR /server
# tcpdump
RUN apk add --update tcpdump
RUN mkdir captured
RUN mkdir captured/server

# openssl
RUN apk add openssl

ENTRYPOINT ["./main"]
