FROM ubuntu:latest

# install mkcert
RUN apt update && \
    apt install -y curl && \
    curl -LO https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64 && \
    mv mkcert-v1.4.4-linux-amd64 /usr/local/bin/mkcert && \
    chmod +x /usr/local/bin/mkcert

RUN apt clean && \
    rm -rf /var/lib/apt/lists/*
