version: "3.8"

services:
  myca:
    container_name: myca
    build:
      context: .
      dockerfile: Dockerfile.CA
    hostname: myca
    volumes:
      - "./mkcert/:/root/"
    tty: true
    stdin_open: true
    networks:
          custom-network:
            ipv4_address: 192.168.1.4

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 443:443
    volumes:
      - ./captured/server:/captured/server
      - ./server/cert:/server/cert
    networks:
        custom-network:
          ipv4_address: 192.168.1.3

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8081:8081
    volumes:
      - ./client/cert:/client/cert
    networks:
          custom-network:
            ipv4_address: 192.168.1.2

# https://docs.docker.com/compose/compose-file/06-networks/
networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
